<?php

namespace App\Enums;

use TiagoF2\Enums\Core\Enum;

class Countries extends Enum
{
    public const AFRICA_DO_SUL = 1001;
    public const AUSTRIA = 1002;
    public const INDIA = 1003;
    public const AFEGANISTAO = 1004;
    public const ALBANIA = 1005;
    public const ALEMANHA = 1006;
    public const ANDORRA = 1007;
    public const ANGOLA = 1008;
    public const ANGUILA = 1009;
    public const ANTARCTIDA = 10010;
    public const ANTIGUA_E_BARBUDA = 10011;
    public const ANTILHAS_NEERLANDESAS = 10012;
    public const ARABIA_SAUDITA = 10013;
    public const ARGELIA = 10014;
    public const ARGENTINA = 10015;
    public const ARMENIA = 10016;
    public const ARUBA = 10017;
    public const AUSTRALIA = 10018;
    public const AZERBAIJAO = 10019;
    public const BELGICA = 10020;
    public const BOSNIA_E_HERZEGOVINA = 10021;
    public const BAAMAS = 10022;
    public const BANGLADECHE = 10023;
    public const BAREM = 10024;
    public const BARBADOS = 10025;
    public const BELIZE = 10026;
    public const BENIM = 10027;
    public const BERMUDAS = 10028;
    public const BIELORRUSSIA = 10029;
    public const BIRMANIA = 10030;
    public const BOLIVIA = 10031;
    public const BOTSUANA = 10032;
    public const BRASIL = 10033;
    public const BRUNEI = 10034;
    public const BULGARIA = 10035;
    public const BURUNDI = 10036;
    public const BURQUINA_FASO = 10037;
    public const BUTAO = 10038;
    public const CABO_VERDE = 10039;
    public const CAMAROES = 10040;
    public const CAMBOJA = 10041;
    public const CANADA = 10042;
    public const CATAR = 10043;
    public const CAZAQUISTAO = 10044;
    public const CHADE = 10045;
    public const CHILE = 10046;
    public const CHINA = 10047;
    public const CHIPRE = 10048;
    public const COLOMBIA = 10049;
    public const COMORES = 10050;
    public const CONGO_BRAZZAVILLE = 10051;
    public const CONGO_KINSHASA = 10052;
    public const COREIA_DO_NORTE = 10053;
    public const COREIA_DO_SUL = 10054;
    public const COSTA_RICA = 10055;
    public const COSTA_DO_MARFIM = 10056;
    public const CROACIA = 10057;
    public const CUBA = 10058;
    public const DINAMARCA = 10059;
    public const DOMINICA = 10060;
    public const EGIPTO = 10061;
    public const EMIRATOS_ARABES_UNIDOS = 10062;
    public const EQUADOR = 10063;
    public const ERITREIA = 10064;
    public const ESLOVAQUIA = 10065;
    public const ESLOVENIA = 10066;
    public const ESPANHA = 10067;
    public const ESTONIA = 10068;
    public const ESTADOS_UNIDOS = 10069;
    public const ETIOPIA = 10070;
    public const FAROE = 10071;
    public const FIJI = 10072;
    public const FILIPINAS = 10073;
    public const FINLANDIA = 10074;
    public const FRANCA = 10075;
    public const GAMBIA = 10076;
    public const GABAO = 10077;
    public const GANA = 10078;
    public const GEORGIA = 10079;
    public const GEORGIA_DO_SUL_E_SANDWICH_DO_SUL = 10080;
    public const GIBRALTAR = 10081;
    public const GRECIA = 10082;
    public const GRANADA = 10083;
    public const GRONELANDIA = 10084;
    public const GUADALUPE = 10085;
    public const GUAME = 10086;
    public const GUATEMALA = 10087;
    public const GUIANA = 10088;
    public const GUIANA_FRANCESA = 10089;
    public const GUINE = 10090;
    public const GUINE_EQUATORIAL = 10091;
    public const GUINE_BISSAU = 10092;
    public const HAITI = 10093;
    public const HONDURAS = 10094;
    public const HONG_KONG = 10095;
    public const HUNGRIA = 10096;
    public const IEMEN = 10097;
    public const ILHA_BOUVET = 10098;
    public const ILHA_NORFOLK = 10099;
    public const ILHA_DO_NATAL = 100100;
    public const ILHAS_CAIMAO = 100101;
    public const ILHAS_COOK = 100102;
    public const ILHAS_FALKLAND = 100103;
    public const ILHAS_HEARD_E_MCDONALD = 100104;
    public const ILHAS_MARSHALL = 100105;
    public const ILHAS_MENORES_DISTANTES_DOS_ESTADOS_UNIDOS = 100106;
    public const ILHAS_SALOMAO = 100107;
    public const ILHAS_TURCAS_E_CAICOS = 100108;
    public const ILHAS_VIRGENS_AMERICANAS = 100109;
    public const ILHAS_VIRGENS_BRITANICAS = 100110;
    public const ILHAS_DOS_COCOS = 100111;
    public const INDONESIA = 100112;
    public const IRAO = 100113;
    public const IRAQUE = 100114;
    public const IRLANDA = 100115;
    public const ISLANDIA = 100116;
    public const ISRAEL = 100117;
    public const ITALIA = 100118;
    public const JAMAICA = 100119;
    public const JAPAO = 100120;
    public const JIBUTI = 100121;
    public const JORDANIA = 100122;
    public const JUGOSLAVIA = 100123;
    public const KUWAIT = 100124;
    public const LIBANO = 100125;
    public const LIBIA = 100126;
    public const LAOS = 100127;
    public const LESOTO = 100128;
    public const LETONIA = 100129;
    public const LIBERIA = 100130;
    public const LISTENSTAINE = 100131;
    public const LITUANIA = 100132;
    public const LUXEMBURGO = 100133;
    public const MEXICO = 100134;
    public const MONACO = 100135;
    public const MACAU = 100136;
    public const MACEDONIA = 100137;
    public const MADAGASCAR = 100138;
    public const MALASIA = 100139;
    public const MALAVI = 100140;
    public const MALDIVAS = 100141;
    public const MALI = 100142;
    public const MALTA = 100143;
    public const MARIANAS_DO_NORTE = 100144;
    public const MARROCOS = 100145;
    public const MARTINICA = 100146;
    public const MAURICIA = 100147;
    public const MAURITANIA = 100148;
    public const MAYOTTE = 100149;
    public const MICRONESIA = 100150;
    public const MOCAMBIQUE = 100151;
    public const MOLDAVIA = 100152;
    public const MONGOLIA = 100153;
    public const MONSERRATE = 100154;
    public const NIGER = 100155;
    public const NAMIBIA = 100156;
    public const NAURU = 100157;
    public const NEPAL = 100158;
    public const NICARAGUA = 100159;
    public const NIGERIA = 100160;
    public const NIUE = 100161;
    public const NORUEGA = 100162;
    public const NOVA_CALEDONIA = 100163;
    public const NOVA_ZELANDIA = 100164;
    public const OMA = 100165;
    public const PAISES_BAIXOS = 100166;
    public const PALAU = 100167;
    public const PANAMA = 100168;
    public const PAPUA_NOVA_GUINE = 100169;
    public const PAQUISTAO = 100170;
    public const PARAGUAI = 100171;
    public const PERU = 100172;
    public const PITCAIRN = 100173;
    public const POLONIA = 100174;
    public const POLINESIA_FRANCESA = 100175;
    public const PORTO_RICO = 100176;
    public const PORTUGAL = 100177;
    public const QUENIA = 100178;
    public const QUIRGUIZISTAO = 100179;
    public const QUIRIBATI = 100180;
    public const RUSSIA = 100181;
    public const REINO_UNIDO = 100182;
    public const REPUBLICA_CENTRO_AFRICANA = 100183;
    public const REPUBLICA_CHECA = 100184;
    public const REPUBLICA_DOMINICANA = 100185;
    public const REUNIAO = 100186;
    public const ROMENIA = 100187;
    public const RUANDA = 100188;
    public const SAO_CRISTOVAO_E_NEVES = 100189;
    public const SAO_MARINHO = 100190;
    public const SAO_PEDRO_E_MIQUELON = 100191;
    public const SAO_TOME_E_PRINCIPE = 100192;
    public const SAO_VICENTE_E_GRANADINAS = 100193;
    public const SIRIA = 100194;
    public const SALVADOR = 100195;
    public const SAMOA = 100196;
    public const SAMOA_AMERICANA = 100197;
    public const SANTA_HELENA = 100198;
    public const SANTA_LUCIA = 100199;
    public const SARA_OCIDENTAL = 100200;
    public const SEICHELES = 100201;
    public const SENEGAL = 100202;
    public const SERRA_LEOA = 100203;
    public const SINGAPURA = 100204;
    public const SOMALIA = 100205;
    public const SRI_LANCA = 100206;
    public const SUECIA = 100207;
    public const SUICA = 100208;
    public const SUAZILANDIA = 100209;
    public const SUDAO = 100210;
    public const SURINAME = 100211;
    public const SVALBARD_E_JAN_MAYEN = 100212;
    public const TAILANDIA = 100213;
    public const TAIWAN = 100214;
    public const TAJIQUISTAO = 100215;
    public const TANZANIA = 100216;
    public const TERRITORIO_BRITANICO_DO_OCEANO_INDICO = 100217;
    public const TERRITORIOS_AUSTRAIS_FRANCESES = 100218;
    public const TIMOR_LESTE = 100219;
    public const TOGO = 100220;
    public const TOKELAU = 100221;
    public const TONGA = 100222;
    public const TRINDADE_E_TOBAGO = 100223;
    public const TUNISIA = 100224;
    public const TURQUEMENISTAO = 100225;
    public const TURQUIA = 100226;
    public const TUVALU = 100227;
    public const UCRANIA = 100228;
    public const UGANDA = 100229;
    public const URUGUAI = 100230;
    public const USBEQUISTAO = 100231;
    public const VANUATU = 100232;
    public const VATICANO = 100233;
    public const VENEZUELA = 100234;
    public const VIETNAME = 100235;
    public const WALLIS_E_FUTUNA = 100236;
    public const ZAMBIA = 100237;
    public const ZIMBABUE = 100238;

    protected static array $enums = [
        self::AFRICA_DO_SUL                             => 'África do Sul',
        self::AUSTRIA                                   => 'Áustria',
        self::INDIA                                     => 'Índia',
        self::AFEGANISTAO                               => 'Afeganistão',
        self::ALBANIA                                   => 'Albânia',
        self::ALEMANHA                                  => 'Alemanha',
        self::ANDORRA                                   => 'Andorra',
        self::ANGOLA                                    => 'Angola',
        self::ANGUILA                                   => 'Anguila',
        self::ANTARCTIDA                                => 'Antárctida',
        self::ANTIGUA_E_BARBUDA                         => 'Antígua e Barbuda',
        self::ANTILHAS_NEERLANDESAS                     => 'Antilhas Neerlandesas',
        self::ARABIA_SAUDITA                            => 'Arábia Saudita',
        self::ARGELIA                                   => 'Argélia',
        self::ARGENTINA                                 => 'Argentina',
        self::ARMENIA                                   => 'Arménia',
        self::ARUBA                                     => 'Aruba',
        self::AUSTRALIA                                 => 'Austrália',
        self::AZERBAIJAO                                => 'Azerbaijão',
        self::BELGICA                                   => 'Bélgica',
        self::BOSNIA_E_HERZEGOVINA                      => 'Bósnia e Herzegovina',
        self::BAAMAS                                    => 'Baamas',
        self::BANGLADECHE                               => 'Bangladeche',
        self::BAREM                                     => 'Barém',
        self::BARBADOS                                  => 'Barbados',
        self::BELIZE                                    => 'Belize',
        self::BENIM                                     => 'Benim',
        self::BERMUDAS                                  => 'Bermudas',
        self::BIELORRUSSIA                              => 'Bielorrússia',
        self::BIRMANIA                                  => 'Birmânia',
        self::BOLIVIA                                   => 'Bolívia',
        self::BOTSUANA                                  => 'Botsuana',
        self::BRASIL                                    => 'Brasil',
        self::BRUNEI                                    => 'Brunei',
        self::BULGARIA                                  => 'Bulgária',
        self::BURUNDI                                   => 'Burúndi',
        self::BURQUINA_FASO                             => 'Burquina Faso',
        self::BUTAO                                     => 'Butão',
        self::CABO_VERDE                                => 'Cabo Verde',
        self::CAMAROES                                  => 'Camarões',
        self::CAMBOJA                                   => 'Camboja',
        self::CANADA                                    => 'Canadá',
        self::CATAR                                     => 'Catar',
        self::CAZAQUISTAO                               => 'Cazaquistão',
        self::CHADE                                     => 'Chade',
        self::CHILE                                     => 'Chile',
        self::CHINA                                     => 'China',
        self::CHIPRE                                    => 'Chipre',
        self::COLOMBIA                                  => 'Colômbia',
        self::COMORES                                   => 'Comores',
        self::CONGO_BRAZZAVILLE                         => 'Congo-Brazzaville',
        self::CONGO_KINSHASA                            => 'Congo-Kinshasa',
        self::COREIA_DO_NORTE                           => 'Coreia do Norte',
        self::COREIA_DO_SUL                             => 'Coreia do Sul',
        self::COSTA_RICA                                => 'Costa Rica',
        self::COSTA_DO_MARFIM                           => 'Costa do Marfim',
        self::CROACIA                                   => 'Croácia',
        self::CUBA                                      => 'Cuba',
        self::DINAMARCA                                 => 'Dinamarca',
        self::DOMINICA                                  => 'Domínica',
        self::EGIPTO                                    => 'Egipto',
        self::EMIRATOS_ARABES_UNIDOS                    => 'Emiratos Árabes Unidos',
        self::EQUADOR                                   => 'Equador',
        self::ERITREIA                                  => 'Eritreia',
        self::ESLOVAQUIA                                => 'Eslováquia',
        self::ESLOVENIA                                 => 'Eslovénia',
        self::ESPANHA                                   => 'Espanha',
        self::ESTONIA                                   => 'Estónia',
        self::ESTADOS_UNIDOS                            => 'Estados Unidos',
        self::ETIOPIA                                   => 'Etiópia',
        self::FAROE                                     => 'Faroé',
        self::FIJI                                      => 'Fiji',
        self::FILIPINAS                                 => 'Filipinas',
        self::FINLANDIA                                 => 'Finlândia',
        self::FRANCA                                    => 'França',
        self::GAMBIA                                    => 'Gâmbia',
        self::GABAO                                     => 'Gabão',
        self::GANA                                      => 'Gana',
        self::GEORGIA                                   => 'Geórgia',
        self::GEORGIA_DO_SUL_E_SANDWICH_DO_SUL          => 'Geórgia do Sul e Sandwich do Sul',
        self::GIBRALTAR                                 => 'Gibraltar',
        self::GRECIA                                    => 'Grécia',
        self::GRANADA                                   => 'Granada',
        self::GRONELANDIA                               => 'Gronelândia',
        self::GUADALUPE                                 => 'Guadalupe',
        self::GUAME                                     => 'Guame',
        self::GUATEMALA                                 => 'Guatemala',
        self::GUIANA                                    => 'Guiana',
        self::GUIANA_FRANCESA                           => 'Guiana Francesa',
        self::GUINE                                     => 'Guiné',
        self::GUINE_EQUATORIAL                          => 'Guiné Equatorial',
        self::GUINE_BISSAU                              => 'Guiné-Bissau',
        self::HAITI                                     => 'Haiti',
        self::HONDURAS                                  => 'Honduras',
        self::HONG_KONG                                 => 'Hong Kong',
        self::HUNGRIA                                   => 'Hungria',
        self::IEMEN                                     => 'Iémen',
        self::ILHA_BOUVET                               => 'Ilha Bouvet',
        self::ILHA_NORFOLK                              => 'Ilha Norfolk',
        self::ILHA_DO_NATAL                             => 'Ilha do Natal',
        self::ILHAS_CAIMAO                              => 'Ilhas Caimão',
        self::ILHAS_COOK                                => 'Ilhas Cook',
        self::ILHAS_FALKLAND                            => 'Ilhas Falkland',
        self::ILHAS_HEARD_E_MCDONALD                    => 'Ilhas Heard e McDonald',
        self::ILHAS_MARSHALL                            => 'Ilhas Marshall',
        self::ILHAS_MENORES_DISTANTES_DOS_ESTADOS_UNIDOS => 'Ilhas Menores Distantes dos Estados Unidos',
        self::ILHAS_SALOMAO                             => 'Ilhas Salomão',
        self::ILHAS_TURCAS_E_CAICOS                     => 'Ilhas Turcas e Caicos',
        self::ILHAS_VIRGENS_AMERICANAS                  => 'Ilhas Virgens Americanas',
        self::ILHAS_VIRGENS_BRITANICAS                  => 'Ilhas Virgens Britânicas',
        self::ILHAS_DOS_COCOS                           => 'Ilhas dos Cocos',
        self::INDONESIA                                 => 'Indonésia',
        self::IRAO                                      => 'Irão',
        self::IRAQUE                                    => 'Iraque',
        self::IRLANDA                                   => 'Irlanda',
        self::ISLANDIA                                  => 'Islândia',
        self::ISRAEL                                    => 'Israel',
        self::ITALIA                                    => 'Itália',
        self::JAMAICA                                   => 'Jamaica',
        self::JAPAO                                     => 'Japão',
        self::JIBUTI                                    => 'Jibuti',
        self::JORDANIA                                  => 'Jordânia',
        self::JUGOSLAVIA                                => 'Jugoslávia',
        self::KUWAIT                                    => 'Kuwait',
        self::LIBANO                                    => 'Líbano',
        self::LIBIA                                     => 'Líbia',
        self::LAOS                                      => 'Laos',
        self::LESOTO                                    => 'Lesoto',
        self::LETONIA                                   => 'Letónia',
        self::LIBERIA                                   => 'Libéria',
        self::LISTENSTAINE                              => 'Listenstaine',
        self::LITUANIA                                  => 'Lituânia',
        self::LUXEMBURGO                                => 'Luxemburgo',
        self::MEXICO                                    => 'México',
        self::MONACO                                    => 'Mónaco',
        self::MACAU                                     => 'Macau',
        self::MACEDONIA                                 => 'Macedónia',
        self::MADAGASCAR                                => 'Madagáscar',
        self::MALASIA                                   => 'Malásia',
        self::MALAVI                                    => 'Malávi',
        self::MALDIVAS                                  => 'Maldivas',
        self::MALI                                      => 'Mali',
        self::MALTA                                     => 'Malta',
        self::MARIANAS_DO_NORTE                         => 'Marianas do Norte',
        self::MARROCOS                                  => 'Marrocos',
        self::MARTINICA                                 => 'Martinica',
        self::MAURICIA                                  => 'Maurícia',
        self::MAURITANIA                                => 'Mauritânia',
        self::MAYOTTE                                   => 'Mayotte',
        self::MICRONESIA                                => 'Micronésia',
        self::MOCAMBIQUE                                => 'Moçambique',
        self::MOLDAVIA                                  => 'Moldávia',
        self::MONGOLIA                                  => 'Mongólia',
        self::MONSERRATE                                => 'Monserrate',
        self::NIGER                                     => 'Níger',
        self::NAMIBIA                                   => 'Namíbia',
        self::NAURU                                     => 'Nauru',
        self::NEPAL                                     => 'Nepal',
        self::NICARAGUA                                 => 'Nicarágua',
        self::NIGERIA                                   => 'Nigéria',
        self::NIUE                                      => 'Niue',
        self::NORUEGA                                   => 'Noruega',
        self::NOVA_CALEDONIA                            => 'Nova Caledónia',
        self::NOVA_ZELANDIA                             => 'Nova Zelândia',
        self::OMA                                       => 'Omã',
        self::PAISES_BAIXOS                             => 'Países Baixos',
        self::PALAU                                     => 'Palau',
        self::PANAMA                                    => 'Panamá',
        self::PAPUA_NOVA_GUINE                          => 'Papua-Nova Guiné',
        self::PAQUISTAO                                 => 'Paquistão',
        self::PARAGUAI                                  => 'Paraguai',
        self::PERU                                      => 'Peru',
        self::PITCAIRN                                  => 'Pitcairn',
        self::POLONIA                                   => 'Polónia',
        self::POLINESIA_FRANCESA                        => 'Polinésia Francesa',
        self::PORTO_RICO                                => 'Porto Rico',
        self::PORTUGAL                                  => 'Portugal',
        self::QUENIA                                    => 'Quénia',
        self::QUIRGUIZISTAO                             => 'Quirguizistão',
        self::QUIRIBATI                                 => 'Quiribáti',
        self::RUSSIA                                    => 'Rússia',
        self::REINO_UNIDO                               => 'Reino Unido',
        self::REPUBLICA_CENTRO_AFRICANA                 => 'República Centro-Africana',
        self::REPUBLICA_CHECA                           => 'República Checa',
        self::REPUBLICA_DOMINICANA                      => 'República Dominicana',
        self::REUNIAO                                   => 'Reunião',
        self::ROMENIA                                   => 'Roménia',
        self::RUANDA                                    => 'Ruanda',
        self::SAO_CRISTOVAO_E_NEVES                     => 'São Cristóvão e Neves',
        self::SAO_MARINHO                               => 'São Marinho',
        self::SAO_PEDRO_E_MIQUELON                      => 'São Pedro e Miquelon',
        self::SAO_TOME_E_PRINCIPE                       => 'São Tomé e Príncipe',
        self::SAO_VICENTE_E_GRANADINAS                  => 'São Vicente e Granadinas',
        self::SIRIA                                     => 'Síria',
        self::SALVADOR                                  => 'Salvador',
        self::SAMOA                                     => 'Samoa',
        self::SAMOA_AMERICANA                           => 'Samoa Americana',
        self::SANTA_HELENA                              => 'Santa Helena',
        self::SANTA_LUCIA                               => 'Santa Lúcia',
        self::SARA_OCIDENTAL                            => 'Sara Ocidental',
        self::SEICHELES                                 => 'Seicheles',
        self::SENEGAL                                   => 'Senegal',
        self::SERRA_LEOA                                => 'Serra Leoa',
        self::SINGAPURA                                 => 'Singapura',
        self::SOMALIA                                   => 'Somália',
        self::SRI_LANCA                                 => 'Sri Lanca',
        self::SUECIA                                    => 'Suécia',
        self::SUICA                                     => 'Suíça',
        self::SUAZILANDIA                               => 'Suazilândia',
        self::SUDAO                                     => 'Sudão',
        self::SURINAME                                  => 'Suriname',
        self::SVALBARD_E_JAN_MAYEN                      => 'Svalbard e Jan Mayen',
        self::TAILANDIA                                 => 'Tailândia',
        self::TAIWAN                                    => 'Taiwan',
        self::TAJIQUISTAO                               => 'Tajiquistão',
        self::TANZANIA                                  => 'Tanzânia',
        self::TERRITORIO_BRITANICO_DO_OCEANO_INDICO     => 'Território Britânico do Oceano Índico',
        self::TERRITORIOS_AUSTRAIS_FRANCESES            => 'Territórios Austrais Franceses',
        self::TIMOR_LESTE                               => 'Timor Leste',
        self::TOGO                                      => 'Togo',
        self::TOKELAU                                   => 'Tokelau',
        self::TONGA                                     => 'Tonga',
        self::TRINDADE_E_TOBAGO                         => 'Trindade e Tobago',
        self::TUNISIA                                   => 'Tunísia',
        self::TURQUEMENISTAO                            => 'Turquemenistão',
        self::TURQUIA                                   => 'Turquia',
        self::TUVALU                                    => 'Tuvalu',
        self::UCRANIA                                   => 'Ucrânia',
        self::UGANDA                                    => 'Uganda',
        self::URUGUAI                                   => 'Uruguai',
        self::USBEQUISTAO                               => 'Usbequistão',
        self::VANUATU                                   => 'Vanuatu',
        self::VATICANO                                  => 'Vaticano',
        self::VENEZUELA                                 => 'Venezuela',
        self::VIETNAME                                  => 'Vietname',
        self::WALLIS_E_FUTUNA                           => 'Wallis e Futuna',
        self::ZAMBIA                                    => 'Zâmbia',
        self::ZIMBABUE                                  => 'Zimbábue',
    ];
}
